config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'about', to: 'pages#about'
  get 'aesthetic', to: 'aesthetics#index'
  get 'contact', to: 'contacts#index'
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aesthetic.rb
class Aesthetic < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, presence: true
  validates :treatment_type, presence: true
  validates :message, presence: true
  
  # Callbacks
  before_save :normalize_name

  # Custom methods
  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def normalize_name
    self.name = name.downcase.titleize
  end
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/aesthetics_controller.rb
class AestheticsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @aesthetics = Aesthetic.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @contacts = Contact.all
    @contact = Contact.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about, ]

  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aesthetics/index.html.erb
<div class="aboutcards">
  <div>
    <%= cl_image_tag("What-is-a-Sports-Massage_w9x5rw", class: "cardbody") %>
    <button class="btn btn-dark">Book Now</button>
  </div>
  <div>
    <h1>This is the main title</h1>
    <p>The quick version:</p>
    <p>Treatment type: [Injectable]</p>
    <p>Results: [How long it lasts]</p>
    <p>Treatment time: [how long it takes]</p>
    <p>Pain Level: [you'll only feel a prick]</p>
  </div>
</div>
<div class="container pt-4">
  <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <button class="btn btn-dark">Book Now</button>
</div>
<div class="aboutcardinner text-center mt-4">
  <h3>FAQ</h3>
  <p>question</p>
  <p>question</p>
  <p>question</p>
  <p>question</p>
</div>

app/views/contacts/index.html.erb
<div class="aboutcardouter">
  <div class="aboutcardinner">
    <div class="aboutcards">
      <div>
        <h1>This is the main titile</h1>
        <h2>This is the secondary title</h2>
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <button class="btn btn-dark">Book Now</button>
      </div>
      <div>
        <%= cl_image_tag("What-is-a-Sports-Massage_w9x5rw", class: "cardbody") %>
      </div>
    </div>
  </div>
</div>
<div class="container pt-2">
  <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
<div class="container pb-2">
  <%= simple_form_for @contact, html: { class: 'row g-3' } do |f| %>

    <div class="col-md-6">
      <%= f.input :name, label: 'Full Name', input_html: { class: 'form-control' } %>
    </div>

    <div class="col-md-6">
      <%= f.input :email, label: 'Email', input_html: { class: 'form-control' } %>
    </div>

    <div class="col-md-6">
      <%= f.input :phone, label: 'Phone Number', input_html: { class: 'form-control' } %>
    </div>

    <div class="col-md-6">
      <%= f.input :treatment_type, label: 'Type of Treatment', collection: ['Massage', 'Physiotherapy', 'Acupuncture'], prompt: 'Select Treatment', input_html: { class: 'form-select' } %>
    </div>

    <div class="col-12">
      <%= f.input :message, as: :text, label: 'Message', input_html: { class: 'form-control', rows: 5 } %>
    </div>

    <div class="col-12">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chapter2aesthetics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="aboutcardouter">
  <div class="aboutcardinner">
    <div class="aboutcards">
      <div>
        <h1>This is the main titile</h1>
        <h2>This is the secondary title</h2>
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <button class="btn btn-dark">Book Now</button>
      </div>
      <div>
        <%= cl_image_tag("What-is-a-Sports-Massage_w9x5rw", class: "cardbody") %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="aboutcards">
    <div>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <div>
      <%= cl_image_tag("What-is-a-Sports-Massage_w9x5rw", class: "cardbody") %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%=cl_image_tag("facial-aesthetics-header-image_d9sfly", class: "mainbanner")  %>
<div class="container pt-3">
  <h1 class="text-center">Welcome to Chapter2aesthitics</h1>

  <div>
      <p>Lorem ipsum dolor sit amet, tempor noster sadipscing in nam. Et quo partem reprehendunt. Te noluisse patrioque cum, pri ad oratio alterum. Duis debet vix eu. Vel quem neglegentur ut, ridens antiopam dissentias id nec.

      Elitr maluisset liberavisse quo ne, ex est justo sensibus incorrupte. Quo quas moderatius in, nemore periculis scriptorem id cum. Sit eu solum efficiantur, ut est bonorum intellegebat. Ridens expetendis ea vix. Congue aperiam verterem ad sed, simul hendrerit honestatis vix eu.

      Persius maiorum ne nec. Duo cu solet dolores mnesarchum, qui id vidisse habemus. Graecis atomorum at eos, id est tollit mnesarchum. Id mel tantas vivendo. Possim persecuti ne vim.

      Velit laoreet sapientem et eum, ei qui homero omnium nusquam. In euismod disputando mel. Modus persecuti ei ius, nec no malorum sententiae. Soleat putent feugait ei vel. Verear philosophia ex has. Est labore iriure eu, nec dolore facilis ei, eam noster deleniti ne. Convenire conceptam te pri, his facete oportere liberavisse et, an per civibus postulant.

      Et mel vidit dolores, feugait vivendum eos ne. Usu clita dictas et, quo illum virtute insolens eu, facete nonumes temporibus ut est. Cu eam eligendi praesent, nonumes civibus ne cum, sea eu dolor comprehensam. Eu qui posse movet, natum iisque alienum te duo.</p>
  </div>

  <div class="text-center">
    <button class="btn btn-dark">Book Now</button>
  </div>

</div>

<div class="d-flex justify-content-center pt-4 pb-5">
  <div class="maincards">
    <div class="maincard">
      <%= cl_image_tag("Certificate-program-in-Medical-Cosmetology-and-Facial-Aesthetics_ka1rk0", class: "cardbody") %>
      <div class="card-body">
        <h5 class="card-title text-center">What is a Sports Massage?</h5>
        <p class="card-text">Sports massage is a form of massage involving the manipulation of soft tissue to benefit a person engaged in regular physical activity. Soft tissue is connective tissue that has not hardened into bone and cartilage; it includes skin, muscles, tendons, ligaments and fascia (a form of connective tissue that lines and ensheathes the other soft tissues).</p>
      </div>
    </div>

    <div class="maincard">
      <%= cl_image_tag("what-is-the-golden-ratio-of-facial-aesthetics_x2co3e", class: "cardbody") %>
      <div class="card-body">
        <h5 class="card-title text-center">What is a Sports Massage?</h5>
        <p class="card-text">Sports massage is a form of massage involving the manipulation of soft tissue to benefit a person engaged in regular physical activity. Soft tissue is connective tissue that has not hardened into bone and cartilage; it includes skin, muscles, tendons, ligaments and fascia (a form of connective tissue that lines and ensheathes the other soft tissues).</p>
      </div>
    </div>

    <div class="maincard">
      <%= cl_image_tag("64b6448c6bbdd08b7602d434_smiling-asian-lady_zh2mwz", class: "cardbody") %>
      <div class="card-body">
        <h5 class="card-title text-center">What is a Sports Massage?</h5>
        <p class="card-text">Sports massage is a form of massage involving the manipulation of soft tissue to benefit a person engaged in regular physical activity. Soft tissue is connective tissue that has not hardened into bone and cartilage; it includes skin, muscles, tendons, ligaments and fascia (a form of connective tissue that lines and ensheathes the other soft tissues).</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="mainfooter">
  <div>
    <button class="btn btn-dark">Book Now</button>
    <div class="d-flex pt-2">
      <h3 class="pe-3">T: 123456789</h3>
      <h3>E:ABC@Abc.com</h3>
    </div>
    <div>
      <a href=""><i class="fa-3x fa-brands fa-facebook"></i></a>
      <a href=""><i class="fa-3x fa-brands fa-instagram"></i></a>
      <a href=""><i class="fa-3x fa-brands fa-linkedin"></i></a>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <p>07707717077</p>
    <% end %>

    <!-- Hamburger menu visible on all screen sizes -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "home", root_path, class: "nav-link" %>
            <%= link_to "About", about_path, class: "nav-link" %>
            <%= link_to "Aesthetics", aesthetic_path, class: "nav-link" %>
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>